### ISSUE TITLE
Some rewrite of router will be needed

### ISSUE THREAD

**Issue by BenjiTheC** [PrepareYourMeal/api-server#1]
Since I may need to touch the backend code, I have the original code base copied and `/client`, `/document` striped out and pushed the backend code into this repository. After reading the code, here is some of my thoughts

1. We may need a major rewrite of responses of route, currently there are a handful of routes that end with `return res.send(//something)`, which is sending a text as response. After the separation of server and client, the communication between client and server will be through JSON format data. So a more reasonable response will be `return res.json(dataObject)`.

2. The aggregation of routes look reasonable except for we can move the `/auth` route out of API as it's not prefixed with `/api/auth` in the Express server. It's nothing severe but we could fix it by the way of rewriting.

3. **Just a note**: I see that in the database part we use Mongoose the define the schema of data object, and directly use Mongo query methods in the routes. If time and resources allowed, it can be beneficial to encapsulate the methods in a separate `/database` folder, and call them in the api layer.

4. I'm not clear with the use of `config` npm package. I see that it's used to grab the configuration file but we can do it without this package, I'm not sure what's the pros and cons of `config` package and .env file(which I find more frequently appear in open source node project).

**Comment by fitandship** [comment]
Definitely agree with step 1. Rewriting now. And I saw the the updates with the login so I will integrate and try it out.
